### ISSUE TITLE
Update to the newest mbedtls version

### ISSUE THREAD

**Issue by StefanHri** [mwarning/mbedtls_ecp_compression#2]
Hi,

thanks for providing this great project! ECC public key compression and decompression are exactly what I need for my project.

However, I noticed that the code does not compile with the newest version of mbedtls. Will it be possible to update the code so that it works with the latest versions of the mbedtls development branch?

Thanks,
Stefan

**Comment by mwarning** [comment]
What is the error?

**Comment by mwarning** [comment]
nvm, fixed it. have fun.
